services:
  app:
    environment:
      ADMIN_EMAIL: (set in compose.override.yaml)
      DSN: postgres://postgres:postgres@postgres/postgres
      OPENID_CLIENT_ID: (set in compose.override.yaml)
      OPENID_CLIENT_SECRET: (set in compose.override.yaml)
      PORT: 8080
      SECRET_KEY: (set in compose.override.yaml)
      SERVER_NAME: localhost:8080
    image: ghcr.io/williamjacksn/yavin
    init: true
    ports:
      - 8080:8080

  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.12
    init: true
    volumes:
      - ./:/home/python/yavin
    working_dir: /home/python/yavin

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/16
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ruff:
    image: ghcr.io/astral-sh/ruff
    volumes:
      - ./:/io

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/yavin
    init: true
    volumes:
      - ./:/home/python/yavin
    working_dir: /home/python/yavin

volumes:
  postgres-data:
