services:
  yavin:
    environment:
      ADMIN_EMAIL: (set in compose.override.yaml)
      DSN: postgres://postgres:postgres@postgres/postgres
      OPENID_CLIENT_ID: (set in compose.override.yaml)
      OPENID_CLIENT_SECRET: (set in compose.override.yaml)
      PORT: 8080
      SECRET_KEY: (set in compose.override.yaml)
      SERVER_NAME: localhost:8080
    image: ghcr.io/williamjacksn/yavin
    init: true
    ports:
      - 8080:8080

  postgres:
    image: postgres:11.15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
