version: '3.8'

services:
  yavin:
    image: ghcr.io/williamjacksn/yavin
    environment:
      DSN: postgres://postgres:postgres@postgres/postgres
      PORT: 8080
      SERVER_NAME: localhost:8080

  postgres:
    image: postgres:11.11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
