version: '3'

services:
  yavin:
    image: williamjackson/yavin
    build: .
    environment:
      DSN: postgres://postgres:postgres@postgres/postgres
      PORT: 8080
      SERVER_NAME: localhost:8080

  postgres:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
