version: '3.7'

services:
  yavin:
    image: docker.pkg.github.com/williamjacksn/yavin/yavin
    build: .
    environment:
      DSN: postgres://postgres:postgres@postgres/postgres
      PORT: 8080
      SERVER_NAME: localhost:8080

  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
