version: '3.8'

services:
  yavin:
    image: ghcr.io/williamjacksn/yavin
    environment:
      DSN: postgres://postgres:postgres@postgres/postgres
      PORT: 8080
      SERVER_NAME: localhost:8080

  postgres:
    image: postgres:11.10-alpine
    environment:
      POSTGRES_PASSWORD: postgres
